#!/usr/bin/env bash

set -e

### constants ##################################################################

this_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

### variables ##################################################################

release_version="$(cat "$this_path/release_version")"
python_version="$(cat "$this_path/python_version")"
if [ "$python_version" == "3" ]; then
  python_cmd="python3"
  pip_cmd="pip3"
else
  python_cmd="python"
  pip_cmd="pip"
fi
### build ######################################################################

BUILD_ARGS="--build-arg PYTHON_VERSION=$python_cmd \
--build-arg PIP_VERSION=$pip_cmd" \
BUILD_DIR="$this_path/.." \
BUILD_VERSION="$release_version"

### build and run tests ########################################################

docker build $BUILD_ARGS --tag "quay.io/charter-ctec/$python_cmd-ubuntu-base:$BUILD_VERSION" "$BUILD_DIR"
